# This starter workflow is for a CMake project running on a single platform. There is a different starter workflow if you need cross-platform coverage.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-multi-platform.yml
name: Pull request gate using CMake and Mull

on:
  pull_request:
    branches: [ "main" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  pr_gate:
    runs-on:
      group: MullRunnerGroup
      labels: self-hosted

    steps:
    - uses: actions/checkout@v4

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: CC=clang-17 CXX=clang++-17 cmake -B ${{github.workspace}}/Tests/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DTEST_COMPILE_OPTIONS="-O0 -fpass-plugin=/usr/lib/mull-ir-frontend-17 -g -grecord-command-line"

    - name: Build
      # Build your program with the given configuration
      run: cmake --build ${{github.workspace}}/Tests/build --config ${{env.BUILD_TYPE}} -j 4

    - name: Unit Testing (Deps)
      working-directory: ${{github.workspace}}/Tests/build
      run: ./test_deps

    - name: Unit Testing (UpOneFromLeaf)
      working-directory: ${{github.workspace}}/Tests/build
      run: ./test_up_one_from_leaf

      # we only want to run this if all the unit tests pass
    - name: Mutation Testing (Deps)
      working-directory: ${{github.workspace}}/Tests/build
      run: /usr/bin/mull-runner-17 --ld-search-path /lib/x86_64-linux-gnu --mutation-score-threshold=100 ./test_deps

      # we only want to run this if all the unit tests pass
    - name: Mutation Testing (UpOneFromLeaf)
      working-directory: ${{github.workspace}}/Tests/build
      run: /usr/bin/mull-runner-17 --ld-search-path /lib/x86_64-linux-gnu --mutation-score-threshold=100 ./test_up_one_from_leaf
